//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineStock
    {
        public int Id { get; set; }
        public int Id_Med { get; set; }
        public int Quanity { get; set; }
        public int Id_Department { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Medicines Medicines { get; set; }
    }
}
