INSERT INTO Category VALUES ('Наркотические анальгетики')
INSERT INTO Category VALUES ('Антибактериальные, противомикробные препараты')
INSERT INTO Category VALUES ('Антидепрессанты и средства нормотимического действия')
INSERT INTO Category VALUES ('Антипсихотические средства')
INSERT INTO Category VALUES ('Антисептические средства')
INSERT INTO Category VALUES ('Антихолинэстеразные средства')
INSERT INTO Category VALUES ('Витамины, макро- и микроэлементы')
INSERT INTO Category VALUES ('Гормоны и средства, влияющие на эндокринную систему и обмен веществ')
INSERT INTO Category VALUES ('Дезинтоксикационное средство')
INSERT INTO Category VALUES ('Заменители плазмы и других компонентов крови, растворы')
INSERT INTO Category VALUES ('Иммуномоделирующее средство')
INSERT INTO Category VALUES ('Метаболические средства')
INSERT INTO Category VALUES ('Ненаркотические анальгетики и нестероидные противовоспалительные средства')
INSERT INTO Category VALUES ('Парентеральное, энтеральное питание')
INSERT INTO Category VALUES ('Противовирусные средства')
INSERT INTO Category VALUES ('Препараты для лечения ВИЧ-инфицированных пациентов')
INSERT INTO Category VALUES ('Иммунные сыворотки')
INSERT INTO Category VALUES ('Противогрибковые средства')
INSERT INTO Category VALUES ('Противоопухолевые, иммунодепрессивные и сопутствующие средства')
INSERT INTO Category VALUES ('Противопротозойные и противопаразитарные средства')
INSERT INTO Category VALUES ('Прочие противовоспалительные средства')
INSERT INTO Category VALUES ('Прочие средства, влияющие на центральную нервную систему')
INSERT INTO Category VALUES ('Противосудорожные средства')
INSERT INTO Category VALUES ('Средства для лечения паркинсонизма')
INSERT INTO Category VALUES ('Спазмолитические средства')
INSERT INTO Category VALUES ('Средства для лечения аллергических реакций')
INSERT INTO Category VALUES ('Средства для лечения заболеваний желудочно-кишечного тракта')
INSERT INTO Category VALUES ('Средства для лечения подагры')
INSERT INTO Category VALUES ('Средства для лечения сахарного диабета')
INSERT INTO Category VALUES ('Средства для наркоза, анестетики, миорелаксанты')
INSERT INTO Category VALUES ('Средства, влияющие на кроветворение, систему свертывания')
INSERT INTO Category VALUES ('Средства, влияющие на органы дыхания')
INSERT INTO Category VALUES ('Средства, влияющие на сердечно-сосудистую систему')
INSERT INTO Category VALUES ('Средства, применяемые в наркологии')
INSERT INTO Category VALUES ('Средства, применяемые в офтальмологии')
INSERT INTO Category VALUES ('Рентгеноконтрастные средства')
INSERT INTO Category VALUES ('Диагностические и терапевтические радиофармацевтические средства')
INSERT INTO Category VALUES ('Препараты для лечения доброкачественной гиперплазии предстательной железы')
INSERT INTO Category VALUES ('Аллергены')
INSERT INTO Category VALUES ('Изделия медицинского назначения')
INSERT INTO Category VALUES ('Лекарственные средства и медицинские изделия, назначаемые и выписываемые по мероприятию «Сахарный диабет»')
